name: Build images

on:
  push:

jobs:
  check:
    name: Check config 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Write secrets file & decrypt
      run: |
        sudo apt-get install -y git-crypt 
        echo ${{ secrets.REPO_SECRETS_KEY }} | base64 -di | zcat > /tmp/repo-key
        git-crypt unlock /tmp/repo-key

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-25.11

    - name: "Build Image ${{ matrix.derivation }}"
      run: |
        nix flake check --all-systems -L 2>&1

