name: Check configuration

on:
  push:
    paths-ignore:
      - '.github/**'
      - '*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.github/**'
      - '*.md'
  workflow_dispatch:

jobs:
  check:
    if: "!startsWith(github.event.head_commit.message, 'Merge pull request')"
    name: "Check config for ${{ matrix.pairs.arch }} -> ${{ matrix.pairs.config }}"
    runs-on: ${{ matrix.pairs.runner }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        pairs: 
          - runner: ubuntu-latest
            arch: x86_64-linux
            config: emily
          - runner: ubuntu-latest
            arch: x86_64-linux
            config: jocelyn 

          - runner: ubuntu-latest-arm
            arch: aarch64-linux
            config: raine
          - runner: ubuntu-latest-arm
            arch: aarch64-linux
            config: liriel
          - runner: ubuntu-latest-arm
            arch: aarch64-linux
            config: mingzhu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-26.05
        extra_nix_config: |
          substituters = http://cache.crys
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nixpkgs-python.cachix.org-1:hxjI7pFxTyuTHn2NkvWCrAUcNZLNS3ZAvfYNuYifcEU= cache.nixos-cuda.org:74DUi4Ye579gUqzH4ziL9IyiJBlDpMRn9MBN8oNan9M= lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc= niri.cachix.org-1:Wv0OmO7PsuocRKzfDoJ3mulSl7Z6oezYhGhR+3W2964= itscrystalline.cachix.org-1:w+aEu6k5Rx3xgUSJPCUhdZSxS919ZJvv9wThPKGVMv4= vicinae.cachix.org-1:1kDrfienkGHPYbkpNj1mWTr7Fm1+zcenzgTizIcI3oc= noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4= harmonia.cache.crys:5IjKpw7rA9DxB2BVvDY/NzD0Zakjn9t9SB40AEpY2Q8=

    - name: Check
      run: |
        nix build .#nixosConfigurations.${{ matrix.pairs.config }}.config.system.build.toplevel --dry-run 2>&1

  check-pkgs:
    if: "!startsWith(github.event.head_commit.message, 'Merge pull request')"
    name: "Check custom packages for ${{ matrix.pairs.arch }}"
    runs-on: ${{ matrix.pairs.runner }} 
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        pairs:
          - runner: ubuntu-latest-arm
            arch: aarch64-linux
          - runner: ubuntu-latest
            arch: x86_64-linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-26.05
        extra_nix_config: |
          substituters = http://cache.crys
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nixpkgs-python.cachix.org-1:hxjI7pFxTyuTHn2NkvWCrAUcNZLNS3ZAvfYNuYifcEU= cache.nixos-cuda.org:74DUi4Ye579gUqzH4ziL9IyiJBlDpMRn9MBN8oNan9M= lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc= niri.cachix.org-1:Wv0OmO7PsuocRKzfDoJ3mulSl7Z6oezYhGhR+3W2964= itscrystalline.cachix.org-1:w+aEu6k5Rx3xgUSJPCUhdZSxS919ZJvv9wThPKGVMv4= vicinae.cachix.org-1:1kDrfienkGHPYbkpNj1mWTr7Fm1+zcenzgTizIcI3oc= noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4= harmonia.cache.crys:5IjKpw7rA9DxB2BVvDY/NzD0Zakjn9t9SB40AEpY2Q8=

    - name: Check
      run: nix flake show . 2>&1

