name: Update flake inputs

on:
  schedule:
    - cron: "0 5 * * *"  # 12AM UTC+7
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update flake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Tailscale
      #   uses: tailscale/github-action@v4
      #   with:
      #     oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      #     oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
      #     tags: tag:ci

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-25.11
          extra_nix_config: |
            extra-substituters = http://cache.crys
            extra-trusted-public-keys = mingzhu:V0KsUipFnrBNsfUD8VI0rFXQpgE3KKJfRby9Jm8cLTQ=
            fallback = true

      - name: Update
        id: update
        run: |
          nix flake update 2>&1 | tee /tmp/update-output.txt
          {
            echo "output<<FLAKE_UPDATE_END"
            cat /tmp/update-output.txt
            echo "FLAKE_UPDATE_END"
          } >> $GITHUB_OUTPUT

      - name: Check
        run: nix flake check --all-systems 2>&1

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "crystal's forgejo actions runner"
          author_email: runner@git.iw2tryhard.dev
          push: true
          message: |
            chore: update flake (automated)

            ${{ steps.update.outputs.output }}
